### ISSUE TITLE
Hash function integration

### ISSUE THREAD

**Issue by suntong** [ekzhu/go-sql-lsh#1]
Hi Eric, 

How are you using this package yourself, since it does not implement any specific locality-sensitive hash function? I.e., I want to know which hash function you are using now to go with it. 

The reason I'm asking is that all these are a bit over my top, could you throw in some examples to integrate the package with some hash functions, say Simhash or MinHash please? 

There are many ready-made go packages out there. I've found many, e.g., [the simplest MinHash](https://github.com/suntong/deduper/blob/trim/minhash/minhash.go), but don't know which ones are good implementation and/or integrate well with `go-sql-lsh`.  Please help. 

BTW, I was drawn here because your answer at https://www.quora.com/What-are-some-good-LSH-implementations. Very nice answer, showing that you are very knowledgeable in this subject.

Thanks

**Comment by ekzhu** [comment]
Hi, thanks for your interest in this project. The short answer is [this minhash package](https://godoc.org/github.com/dgryski/go-minhash#MinWise.Signature). The `Signature()` method of `MinWise` produces a slice of `unit64`, which is the type `Signature` in this package (after type conversion from uint64 to uint). You can then insert/query this signature using `SqlLsh` provided in this package.

The MinHash package you found seems to be a MinHash LSH implementation. Thus probably not directly compatible with this package. 

Hope this helps.

**Comment by suntong** [comment]
Oh, thanks a lot for the reply. Really appreciate it. 

I thought you have a package of you own. :-). You must have picked it out from the crowd and found it  good enough for you. (honestly, that even come under my radar, i.e., that wasn't even in my to-check list). 

Just one question, does it handle Chinese well? Do you need to deal with Chinese in your daily life? Do you have any plan to write your own MinHash that can distinguish Chinese words, not just letters, say by package like https://github.com/huichen/sego? 

Thanks again.

**Comment by ekzhu** [comment]
I use the aforementioned package for MinHash. Just an additional note, you need to make sure to seed two different hash functions for `MinWise`. See [this issue](https://github.com/dgryski/go-minhash/pull/1) for details.

For Chinese, you can simply use the characters. Golang handles that perfectly. When you add the characters into MinHash (i.e. `Push()`), just convert them into bytes first. There is no need to have a different MinHash for Chinese.

**Comment by suntong** [comment]
Thanks!

**Comment by suntong** [comment]
Hi Eric,

Would it be possible that you provide a simple sample code that put `go-sql-lsh` and `go-minhash` together please? 

I've tried several times, but all aborted half way as there are so much to read to put together even a simple sample code. 

Thanks

**Comment by ekzhu** [comment]
Hi,

Sorry I don't have any sample code for you right now. I may write a more detailed README with some sample code in the future, but currently I cannot find time to work on it.

For now your best bet may be reading these two links:
1. https://github.com/dgryski/go-minhash/pull/1, a discussion on how to properly use the `go-minhash` package. You can use the `Signature()` function of `Minwise` class to export the MinHash signature.
2. https://github.com/ekzhu/go-sql-lsh/blob/master/sqlite_benchmark_test.go, the benchmark code provides a simple example of how to index signatures using `SqlLsh`. Note this benchmark code uses randomly generated signatures, which are essentially arrays of `uint`.

**Comment by suntong** [comment]
OK. NP. looking forward to your detailed README, and thanks for the links. I'm starting to check them out.

**Comment by suntong** [comment]
**Q1:** Your [Insert](https://godoc.org/github.com/ekzhu/go-sql-lsh#SqlLsh.Insert) need a `k*l` array (i.e., depends on `k` and `l`), while `go-minhash`'s [Signature](https://godoc.org/github.com/dgryski/go-minhash#MinWise.Signature) only gives fix-sized array. 

So how were you able to use `go-minhash` with various `k` and `l`? Or, what `k` and `l` did you use to go with `go-minhash`? Since their data type are different, did you use a loop to do type conversion or there is a simpler way? 

**Q2:** in https://github.com/ekzhu/go-sql-lsh/blob/master/sqlite_benchmark_test.go, there is a `func runSqlite` with parameters of `k, l, n, nq` of `int`, what are the meanings of those variables? 

**Q3:** 

> Inside a relational database, an LSH index is a table, each Signature is a row, and each locality-sensitive hash function's hash values form a column. 

So suppose I want to use a linear combination of 2 hash functions, how to put those two hash values into the database LSH index table?

Thanks

**Comment by ekzhu** [comment]
Q1: picking `k` and `l` depends on your requirement for the balance between precision and recall. Increase `k` (decreasing `l`) gives your higher precision and decreasing `k` (increasing `l`) gives you higher recall. `k*l` is a constant which equals the minhash signature size. See http://infolab.stanford.edu/~ullman/mmds/ch3.pdf for details.

For the type difference you can use a loop to do type conversion, or modify the minhash code.

Q2: `n` is the number of signatures to index, `nq` is the number of queries. `k` and `l` are the LSH parameters.

Q3: a linear combination of 2 hash functions gives you 1 hash value.
